"""Project-wide configuration constants for reproducibility."""

from __future__ import annotations

RANDOM_SEED = 42
TRAIN_SPLIT = 0.8
VALIDATION_SPLIT = 0.1
TEST_SPLIT = 0.1
TFIDF_MAX_FEATURES = 20000
NEURAL_HIDDEN_DIM_1 = 256
NEURAL_HIDDEN_DIM_2 = 64
NEURAL_DROPOUT_1 = 0.3
NEURAL_DROPOUT_2 = 0.2
NEURAL_LEARNING_RATE = 1e-3
NEURAL_MAX_EPOCHS = 20
NEURAL_EARLY_STOPPING_PATIENCE = 4
